import mongoose from "mongoose";
import { sendApiError } from "./apiErrors.js";

const EMPLOYEE_ID_MAX_LENGTH = 100;
const EMPLOYEE_NAME_MAX_LENGTH = 120;
const EMPLOYEE_SEARCH_MAX_LENGTH = 120;
const EMPLOYEE_FILTER_MAX_LENGTH = 80;

const EMPLOYEE_GENDER_OPTIONS = new Set(["Male", "Female", "Other"]);
const EMPLOYEE_TYPE_OPTIONS = new Set(["Full-time", "Part-time"]);

const CREATE_MUTATION_FIELDS = new Set([
  "employeeId",
  "firstName",
  "lastName",
  "gender",
  "ethnicity",
  "employmentType",
  "isShareholder",
  "departmentId",
  "hireDate",
  "birthDate",
  "vacationDays",
  "paidToDate",
  "paidLastYear",
  "payRate",
  "payRateId",
]);

const UPDATE_MUTATION_FIELDS = new Set([
  "firstName",
  "lastName",
  "gender",
  "ethnicity",
  "employmentType",
  "isShareholder",
  "departmentId",
  "hireDate",
  "birthDate",
  "vacationDays",
  "paidToDate",
  "paidLastYear",
  "payRate",
  "payRateId",
]);

const RESERVED_MUTATION_MESSAGES = {
  employeeId: "employeeId cannot be changed after creation because downstream Payroll uses it as the integration key.",
  annualEarnings: "annualEarnings is derived by the dashboard aggregation job and cannot be edited from employee CRUD endpoints.",
  annualEarningsYear: "annualEarningsYear is derived by the dashboard aggregation job and cannot be edited from employee CRUD endpoints.",
  _id: "_id is generated by MongoDB and cannot be provided by clients.",
  createdAt: "createdAt is managed by persistence and cannot be provided by clients.",
  updatedAt: "updatedAt is managed by persistence and cannot be provided by clients.",
};

export class EmployeeContractError extends Error {
  constructor(message, { statusCode = 422, errors = [] } = {}) {
    super(message);
    this.name = "EmployeeContractError";
    this.statusCode = statusCode;
    this.errors = errors;
  }
}

const addError = (errors, field, message, value) => {
  errors.push({
    field,
    message,
    ...(value !== undefined ? { value } : {}),
  });
};

const assertNoValidationErrors = (errors) => {
  if (errors.length > 0) {
    throw new EmployeeContractError("Validation failed.", { errors });
  }
};

const normalizePositiveInteger = ({
  value,
  field,
  defaultValue,
  min = 1,
  max = Number.MAX_SAFE_INTEGER,
  errors,
}) => {
  if (value === undefined || value === null || String(value).trim() === "") {
    return defaultValue;
  }

  const raw = String(value).trim();
  if (!/^\d+$/.test(raw)) {
    addError(errors, field, `${field} must be an integer between ${min} and ${max}.`, value);
    return defaultValue;
  }

  const parsed = Number.parseInt(raw, 10);
  if (parsed < min || parsed > max) {
    addError(errors, field, `${field} must be an integer between ${min} and ${max}.`, value);
    return defaultValue;
  }

  return parsed;
};

const normalizeOptionalSearch = ({
  value,
  field = "search",
  maxLength = EMPLOYEE_SEARCH_MAX_LENGTH,
  errors,
}) => {
  if (value === undefined || value === null) {
    return undefined;
  }

  const normalized = String(value).trim();
  if (!normalized) {
    return undefined;
  }

  if (normalized.length > maxLength) {
    addError(errors, field, `${field} must be at most ${maxLength} characters.`, normalized);
    return undefined;
  }

  return normalized;
};

const normalizeRequiredString = ({
  value,
  field,
  label,
  maxLength,
  errors,
}) => {
  const normalized = value === undefined || value === null ? "" : String(value).trim();
  if (!normalized) {
    addError(errors, field, `${label} is required.`, value);
    return undefined;
  }
  if (normalized.length > maxLength) {
    addError(errors, field, `${label} must be at most ${maxLength} characters.`, normalized);
    return undefined;
  }
  return normalized;
};

const normalizeOptionalString = ({
  value,
  field,
  label,
  maxLength,
  errors,
}) => {
  if (value === undefined || value === null || String(value).trim() === "") {
    return undefined;
  }
  const normalized = String(value).trim();
  if (normalized.length > maxLength) {
    addError(errors, field, `${label} must be at most ${maxLength} characters.`, normalized);
    return undefined;
  }
  return normalized;
};

const normalizeOptionalEnum = ({
  value,
  field,
  label,
  allowedValues,
  errors,
}) => {
  if (value === undefined || value === null || String(value).trim() === "") {
    return undefined;
  }
  const normalized = String(value).trim();
  if (!allowedValues.has(normalized)) {
    addError(errors, field, `${label} must be one of: ${Array.from(allowedValues).join(", ")}.`, value);
    return undefined;
  }
  return normalized;
};

const normalizeOptionalBoolean = ({
  value,
  field,
  label,
  errors,
}) => {
  if (value === undefined || value === null || value === "") {
    return undefined;
  }
  if (typeof value === "boolean") {
    return value;
  }
  if (value === "true") return true;
  if (value === "false") return false;
  addError(errors, field, `${label} must be a boolean value.`, value);
  return undefined;
};

const normalizeOptionalNumber = ({
  value,
  field,
  label,
  errors,
  integer = false,
  min = 0,
}) => {
  if (value === undefined || value === null || value === "") {
    return undefined;
  }

  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    addError(errors, field, `${label} must be a valid number.`, value);
    return undefined;
  }
  if (parsed < min) {
    addError(errors, field, `${label} cannot be less than ${min}.`, value);
    return undefined;
  }
  if (integer && !Number.isInteger(parsed)) {
    addError(errors, field, `${label} must be a whole number.`, value);
    return undefined;
  }
  return parsed;
};

const normalizeOptionalDate = ({
  value,
  field,
  label,
  errors,
}) => {
  if (value === undefined || value === null || value === "") {
    return undefined;
  }
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    addError(errors, field, `${label} must be a valid ISO date.`, value);
    return undefined;
  }
  return parsed.toISOString();
};

const normalizeOptionalDepartmentId = ({
  value,
  errors,
}) => {
  if (value === undefined || value === null || String(value).trim() === "") {
    return undefined;
  }
  const normalized = String(value).trim();
  if (!mongoose.Types.ObjectId.isValid(normalized)) {
    addError(errors, "departmentId", "departmentId must be a valid Mongo ObjectId.", value);
    return undefined;
  }
  return normalized;
};

const normalizeMutationKeys = ({
  payload,
  mode,
  errors,
}) => {
  const allowedFields = mode === "create" ? CREATE_MUTATION_FIELDS : UPDATE_MUTATION_FIELDS;
  Object.keys(payload).forEach((field) => {
    if (field === "employeeId" && mode === "create") {
      return;
    }
    if (RESERVED_MUTATION_MESSAGES[field]) {
      addError(errors, field, RESERVED_MUTATION_MESSAGES[field], payload[field]);
      return;
    }
    if (!allowedFields.has(field)) {
      addError(errors, field, `${field} is not allowed in employee ${mode} payloads.`, payload[field]);
    }
  });
};

export const normalizeEmployeeMutationPayload = (payload = {}, { mode = "create" } = {}) => {
  const errors = [];
  const source = payload && typeof payload === "object" ? payload : {};
  normalizeMutationKeys({ payload: source, mode, errors });

  const normalized = {
    ...(mode === "create" ? {
      employeeId: normalizeRequiredString({
        value: source.employeeId,
        field: "employeeId",
        label: "Employee ID",
        maxLength: EMPLOYEE_ID_MAX_LENGTH,
        errors,
      }),
    } : {}),
    firstName: mode === "create"
      ? normalizeRequiredString({
        value: source.firstName,
        field: "firstName",
        label: "First name",
        maxLength: EMPLOYEE_NAME_MAX_LENGTH,
        errors,
      })
      : normalizeOptionalString({
        value: source.firstName,
        field: "firstName",
        label: "First name",
        maxLength: EMPLOYEE_NAME_MAX_LENGTH,
        errors,
      }),
    lastName: normalizeOptionalString({
      value: source.lastName,
      field: "lastName",
      label: "Last name",
      maxLength: EMPLOYEE_NAME_MAX_LENGTH,
      errors,
    }),
    gender: normalizeOptionalEnum({
      value: source.gender,
      field: "gender",
      label: "Gender",
      allowedValues: EMPLOYEE_GENDER_OPTIONS,
      errors,
    }),
    ethnicity: normalizeOptionalString({
      value: source.ethnicity,
      field: "ethnicity",
      label: "Ethnicity",
      maxLength: EMPLOYEE_NAME_MAX_LENGTH,
      errors,
    }),
    employmentType: normalizeOptionalEnum({
      value: source.employmentType,
      field: "employmentType",
      label: "Employment type",
      allowedValues: EMPLOYEE_TYPE_OPTIONS,
      errors,
    }),
    isShareholder: normalizeOptionalBoolean({
      value: source.isShareholder,
      field: "isShareholder",
      label: "Shareholder flag",
      errors,
    }),
    departmentId: normalizeOptionalDepartmentId({
      value: source.departmentId,
      errors,
    }),
    hireDate: normalizeOptionalDate({
      value: source.hireDate,
      field: "hireDate",
      label: "Hire date",
      errors,
    }),
    birthDate: normalizeOptionalDate({
      value: source.birthDate,
      field: "birthDate",
      label: "Birth date",
      errors,
    }),
    vacationDays: normalizeOptionalNumber({
      value: source.vacationDays,
      field: "vacationDays",
      label: "Vacation days",
      errors,
      integer: true,
    }),
    paidToDate: normalizeOptionalNumber({
      value: source.paidToDate,
      field: "paidToDate",
      label: "Paid to date",
      errors,
    }),
    paidLastYear: normalizeOptionalNumber({
      value: source.paidLastYear,
      field: "paidLastYear",
      label: "Paid last year",
      errors,
    }),
    payRate: normalizeOptionalNumber({
      value: source.payRate,
      field: "payRate",
      label: "Pay rate",
      errors,
    }),
    payRateId: normalizeOptionalNumber({
      value: source.payRateId,
      field: "payRateId",
      label: "Pay rate ID",
      errors,
      integer: true,
    }),
  };

  if (normalized.birthDate && normalized.hireDate && new Date(normalized.birthDate) >= new Date(normalized.hireDate)) {
    const message = "Birth date must be earlier than hire date.";
    addError(errors, "birthDate", message, source.birthDate);
    addError(errors, "hireDate", message, source.hireDate);
  }

  const compact = Object.fromEntries(
    Object.entries(normalized).filter(([, value]) => value !== undefined),
  );

  if (mode === "update" && Object.keys(compact).length === 0) {
    addError(errors, "payload", "At least one editable employee field must be provided for update.");
  }

  assertNoValidationErrors(errors);
  return compact;
};

export const normalizeEmployeeListQuery = (query = {}) => {
  const errors = [];
  const page = normalizePositiveInteger({
    value: query.page,
    field: "page",
    defaultValue: 1,
    max: 100000,
    errors,
  });
  const limit = normalizePositiveInteger({
    value: query.limit,
    field: "limit",
    defaultValue: 50,
    max: 200,
    errors,
  });
  const search = normalizeOptionalSearch({
    value: query.search,
    field: "search",
    errors,
  });
  const departmentId = normalizeOptionalSearch({
    value: query.departmentId,
    field: "departmentId",
    maxLength: EMPLOYEE_FILTER_MAX_LENGTH,
    errors,
  });
  const employmentType = normalizeOptionalSearch({
    value: query.employmentType,
    field: "employmentType",
    maxLength: EMPLOYEE_FILTER_MAX_LENGTH,
    errors,
  });

  assertNoValidationErrors(errors);

  return {
    page,
    limit,
    search,
    departmentId,
    employmentType,
    skip: (page - 1) * limit,
  };
};

export const normalizeEmployeeLookupParam = (value, field = "employeeId") => {
  const errors = [];
  const normalized = value === undefined || value === null
    ? ""
    : String(value).trim();

  if (!normalized) {
    addError(errors, field, `${field} must be a non-empty string.`, value);
  } else if (normalized.length > EMPLOYEE_ID_MAX_LENGTH) {
    addError(
      errors,
      field,
      `${field} must be at most ${EMPLOYEE_ID_MAX_LENGTH} characters.`,
      normalized,
    );
  }

  assertNoValidationErrors(errors);

  return normalized;
};

export const buildEmployeeMeta = ({
  dataset,
  filters = {},
  ...rest
}) => ({
  dataset,
  filters,
  ...rest,
});

export const sendEmployeeContractError = (res, error) => {
  return sendApiError(res, error, { defaultCode: "VALIDATION_ERROR" });
};

export const isMongoObjectId = (value) => mongoose.Types.ObjectId.isValid(value);
